// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace TheDataLibrary.DBModels
{
    public partial class Pizzastopping
    {
        public int IdPizzastoppings { get; set; }
        public int IdPizzas { get; set; }
        public int IdToppings { get; set; }

        public virtual Pizza IdPizzasNavigation { get; set; }
        public virtual Topping IdToppingsNavigation { get; set; }
    }
}